env:
  commonjs: true
  es6: true
  "jest/globals": true
extends:
  - "plugin:jest/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
plugins:
  - "@typescript-eslint"
  - "jest"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    module: true
  project: "./tsconfig.json"
  tsconfigRootDir: "./"
rules:
  "@typescript-eslint/no-explicit-any": 0
