import main from "../03_Template_Method/template_method";
test("consoleに表示される", (): void => {
  const spyLog = jest
    .spyOn(console, "log")
    .mockImplementation((x: any): any => x);
  main();
  expect(spyLog.mock.calls[0][0]).toEqual("<<");
  expect(spyLog.mock.calls[1][0]).toEqual("H");
  expect(spyLog.mock.calls[2][0]).toEqual("H");
  expect(spyLog.mock.calls[3][0]).toEqual("H");
  expect(spyLog.mock.calls[4][0]).toEqual("H");
  expect(spyLog.mock.calls[5][0]).toEqual("H");
  expect(spyLog.mock.calls[6][0]).toEqual(">>");
  expect(spyLog.mock.calls[7][0]).toEqual("+");
  expect(spyLog.mock.calls[8][0]).toEqual("-");
  expect(spyLog.mock.calls[9][0]).toEqual("-");
  expect(spyLog.mock.calls[10][0]).toEqual("-");
  expect(spyLog.mock.calls[11][0]).toEqual("-");
  expect(spyLog.mock.calls[12][0]).toEqual("-");
  expect(spyLog.mock.calls[13][0]).toEqual("-");
  expect(spyLog.mock.calls[14][0]).toEqual("-");
  expect(spyLog.mock.calls[15][0]).toEqual("-");
  expect(spyLog.mock.calls[16][0]).toEqual("-");
  expect(spyLog.mock.calls[17][0]).toEqual("-");
  expect(spyLog.mock.calls[18][0]).toEqual("-");
  expect(spyLog.mock.calls[19][0]).toEqual("-");
  expect(spyLog.mock.calls[20][0]).toEqual("-");
  expect(spyLog.mock.calls[21][0]).toEqual("+");
  expect(spyLog.mock.calls[22][0]).toEqual("|Hello, World.|");
  expect(spyLog.mock.calls[23][0]).toEqual("|Hello, World.|");
  expect(spyLog.mock.calls[24][0]).toEqual("|Hello, World.|");
  expect(spyLog.mock.calls[25][0]).toEqual("|Hello, World.|");
  expect(spyLog.mock.calls[26][0]).toEqual("|Hello, World.|");
  expect(spyLog.mock.calls[27][0]).toEqual("+");
  expect(spyLog.mock.calls[28][0]).toEqual("-");
  expect(spyLog.mock.calls[29][0]).toEqual("-");
  expect(spyLog.mock.calls[30][0]).toEqual("-");
  expect(spyLog.mock.calls[31][0]).toEqual("-");
  expect(spyLog.mock.calls[32][0]).toEqual("-");
  expect(spyLog.mock.calls[33][0]).toEqual("-");
  expect(spyLog.mock.calls[34][0]).toEqual("-");
  expect(spyLog.mock.calls[35][0]).toEqual("-");
  expect(spyLog.mock.calls[36][0]).toEqual("-");
  expect(spyLog.mock.calls[37][0]).toEqual("-");
  expect(spyLog.mock.calls[38][0]).toEqual("-");
  expect(spyLog.mock.calls[39][0]).toEqual("-");
  expect(spyLog.mock.calls[40][0]).toEqual("-");
  expect(spyLog.mock.calls[41][0]).toEqual("+");
  expect(spyLog.mock.calls[42][0]).toEqual("+");
  expect(spyLog.mock.calls[43][0]).toEqual("-");
  expect(spyLog.mock.calls[44][0]).toEqual("-");
  expect(spyLog.mock.calls[45][0]).toEqual("-");
  expect(spyLog.mock.calls[46][0]).toEqual("-");
  expect(spyLog.mock.calls[46][0]).toEqual("-");
  expect(spyLog.mock.calls[47][0]).toEqual("-");
  expect(spyLog.mock.calls[48][0]).toEqual("-");
  expect(spyLog.mock.calls[49][0]).toEqual("+");
  expect(spyLog.mock.calls[50][0]).toEqual("|こんにちは。|");
  expect(spyLog.mock.calls[51][0]).toEqual("|こんにちは。|");
  expect(spyLog.mock.calls[52][0]).toEqual("|こんにちは。|");
  expect(spyLog.mock.calls[53][0]).toEqual("|こんにちは。|");
  expect(spyLog.mock.calls[54][0]).toEqual("|こんにちは。|");
  expect(spyLog.mock.calls[55][0]).toEqual("+");
  expect(spyLog.mock.calls[56][0]).toEqual("-");
  expect(spyLog.mock.calls[57][0]).toEqual("-");
  expect(spyLog.mock.calls[58][0]).toEqual("-");
  expect(spyLog.mock.calls[59][0]).toEqual("-");
  expect(spyLog.mock.calls[60][0]).toEqual("-");
  expect(spyLog.mock.calls[61][0]).toEqual("-");
  expect(spyLog.mock.calls[62][0]).toEqual("+");
  spyLog.mockReset();
  spyLog.mockRestore();
});
